### ISSUE TITLE
View Index Not Found

### ISSUE THREAD

**Issue by abunour22** [srph/e-dental#1]
Thank you for your project .. Unfortunately this error appears !! 

InvalidArgumentException
View [index] not found. 

How can i solve it ?!

**Comment by srph** [comment]
In which route?

**Comment by abunour22** [comment]
as in ( localhost/admin )

this error occurs ,, 
Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException
        throw new NotFoundHttpException();
at line 5751

**Comment by srph** [comment]
Ayy, my bad. It should `localhost/dashboard`.

Sorry for the late replies!
